### ISSUE TITLE
List o' Compliments

### ISSUE THREAD

**Issue by jokosanyang** [FAC-Sixteen/RK-The-Long-Grass#11]
![](https://media.giphy.com/media/YLHwkqayc1j7a/giphy.gif)
I'll just put them all in the same place so it's easier to close them:
- Love the font
- Cute af (in the most positive way) favicon
- Fun game
- Beating your own/friend's high score gives the game a competitive element
- The nostalgia!

**Comment by jokosanyang** [comment]
- Very readable code :+1:

**Comment by dubhcait** [comment]
Thanks
