### ISSUE TITLE
✨Love it! ✨

### ISSUE THREAD

**Issue by aniablaziak** [FAC-Sixteen/RK-The-Long-Grass#7]
Really cool design and a great game overall! Nice that you also included instructions on how to play. 
Possible stretch goal: I'd be great if you mixed all the Pokemon types together and the user would only be awarded points for catching Pokemons of a certain type. 
![](https://media.giphy.com/media/lM86pZcDxfx5e/giphy.gif)

**Comment by dubhcait** [comment]
<3
